#!/usr/bin/env bash
# UserBot
# Copyright (C) 2021-2023 TeamUltroid
#
# This file is a part of < https://github.com/TeamUltroid/Ultroid/ >
# PLease read the GNU Affero General Public License in <https://www.github.com/TeamUltroid/Ultroid/blob/main/LICENSE/>.


echo "
            
╭╮╱╭╮╱╱╱╱╱╱╱╭╮╱╱╱╱╭╮
┃┃╱┃┃╱╱╱╱╱╱╱┃┃╱╱╱╭╯╰╮
┃┃╱┃┣━━┳━━┳━┫╰━┳━┻╮╭╯
┃┃╱┃┃━━┫┃━┫╭┫╭╮┃╭╮┃┃
┃╰━╯┣━━┃┃━┫┃┃╰╯┃╰╯┃╰╮
╰━━━┻━━┻━━┻╯╰━━┻━━┻━╯

      Visit @xteam_cloner for updates!!

"
python3 -m pyUltroid; python3 -m src
